# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: restore
      run: |
        dotnet restore
    - name: build
      run: |
        dotnet build --no-restore -c Release
    - name: push NuGet.org
      run: |
        for file in **/*.nupkg
        do
          dotnet nuget push $file --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate --source https://api.nuget.org/v3/index.json
        done
      
